### ISSUE TITLE
省市区联动method01.js编码有问题，会影响其他js运行

### ISSUE THREAD

**Issue by hengke** [visugar/FrontEnd-examples#3]
function $(str) {
    return document.getElementById(str);
}
会重载$()方法，会影响其他js形如$('.')或$('#')获取对象建议修改为：
// function $(str) {
//     return document.getElementById(str);
// }

var addrShow = document.getElementById('destination');
var prov = document.getElementById('prov');
var city = document.getElementById('city');
var country = document.getElementById('country');

**Comment by visugar** [comment]
已修改
