### ISSUE TITLE
数据有误，172个“城关镇”？

### ISSUE THREAD

**Issue by Panfen** [visugar/FrontEnd-examples#4]
{
                label: "洛阳市",
                districtAndCounty: ["西工区", "老城区", "瀍河回族区", "涧西区", "吉利区", "洛龙区", "偃师市", "孟津县", "城关镇", "新安县", "城关镇", "栾川县", "城关镇", "嵩县", "城关镇", "汝阳县", "城关镇", "宜阳县", "城关镇", "洛宁县", "城关镇", "伊川县", "城关镇"]
            },
一个地区这么多城关镇？？？

**Comment by visugar** [comment]
已修改
